### ISSUE TITLE
org quota configurability 

### ISSUE THREAD

**Issue by lerytke** [cloudfoundry/uptimer#15]
would be nice to be able to set the quota in the config file.  When we deploy and test we get too many apps and fills up the quota.

**Comment by heyjcollins** [comment]
Hi @lerytke - could you please describe your use case in more detail?
Not sure which quota limit you're hitting and need more info.
Uptimer creates it's own orgs, so you shouldn't be hitting the org limits that are set.

Please describe more what you would like to have in the config, provide an example config and a description of the desired uptimer behavior?

**Comment by heyjcollins** [comment]
I haven't heard back on this so I'm going to go ahead and close it. Please re-open if/when you'd like to proceed.

Thanks so much,

Josh
