### ISSUE TITLE
New Feature: Measure uptime of the "TCP routing"

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/uptimer#16]
Can uptimer test the availability of tcp routing of application?
E.g. After `cf p myapp -d tcp-apps-domain.com --random-route`, my app is running on `tcp-apps-domain.com:60073`. Uptimer can test the availability by curling `tcp-apps-domain.com:60073`.

**Comment by heyjcollins** [comment]
Hey @bingosummer  - thanks for this suggestion. Right now this is pretty low priority for the release integration team despite it being a potentially valuable feature to add to uptimer.

As such, would you be interested/willing to submit a PR for this?

Hope you're well!

Josh

**Comment by heyjcollins** [comment]
Hi @bingosummer,
I'm cleaning up a bit and see this this thread has been silent since the end of July.
I'll close the issue for now and if you want to strike up the conversation again, please just go ahead and open it.

Thanks a lot,

Josh
