### ISSUE TITLE
Make uptimer self contained

### ISSUE THREAD

**Issue by zmb3** [cloudfoundry/uptimer#22]
Uptimer has some not-very-visible requirements that are easy to get tripped up on and make running the tool in different environments more difficult than it should be.

The most prominent example of this is the cf push tests.  For these tests to function, it's not enough to simply build the uptimer binary and copy it to your target machine (which is a pretty common workflow to those familiar with Go).  Due to the way the sample app is compiled prior to push tests, uptimer requires that the source code of the app is installed on the machine it runs on, and that there's a valid Go toolchain on the machine to do the compilation.

It would be much more convenient if uptimer packaged the same app into the binary, so that it could be copied to machines without a Go development environment.

I can think of two ways to support this, and am happy to contribute the changes if we agree on a path forward:

1. Don't compile and `cf push` a binary.  Instead push source code, and rely on the Go buildpack to build the binary as part of the push workflow.  This is the simplest approach, as the tool can embed the source code as a giant string contstant, write it to a temp directory, and cf push.  The downside here is that the push workflow will fail if there's not a Go buildpack in the target environment.  Is this something that we need to protect against?

2. [Cross] Compile the test app as part of the build process, and embed the result into the uptimer binary using one of the popular OSS embedding libraries (until Go 1.16 ships with native support for embedding).  This would make the build process a little more difficult, but preserves the existing behavior of pushing a binary and procfile to the target environment.  The new build process could be captured in a script or makefile to ensure that it's done correctly and consistently.

Thoughts?

**Comment by davewalter** [comment]
Hi @zmb3,

Thanks for writing up this issue. We can definitely see how this is less than ideal. After discussing the issue at our team's technical forum this morning, we would be happy to move forward with option 1 to see if that provides a better overall user experience. Looking forward to seeing a PR soon!

Dave and @Birdrock

**Comment by zmb3** [comment]
Awesome, thanks for the quick response @davewalter - will put something together!

**Comment by zmb3** [comment]
So I put together an example of option 1 and it works great for the push-ability test.  The code in `main.go` became a 30-line string constant and we're able to write to a temp file at runtime and push it and the tests run as expected.

Minor issue when it comes to the syslog sink tests, as that program is not self contained - it depends on the `rfc5424` package, so it's more difficult to just have the entire program in a constant.

Seeing several options here:

1. Manually vendor (ie copy) the required code from the rfc5424 package into the large string constant so that we have the entire program represented as a single string.  This works, but results in a rather large file that's a pain to keep in sync with upstream.   Note that the rfc5424 package hasn't been touched in over 2 years, so maybe this isn't a huge concern.

2. Change gears and take option #2 from the original proposal, which would have us package a cross-compiled binary and push that with the binary buildpack.

3. Eliminate the vendor directory from the syslog test app, and just push up the contents of main.go and the dep metadata.  With this approach, we're back to a single, easy-to-manage string constant, but we'd be relying on the buildpack to pull down the rfc5424 dependency.  The downside is the syslog sink tests won't be able to run against offline environments where the buildpack does not have access to the internet to download the dependency.  As with before, I'm not sure how big of a problem this is, since the test already can be disabled for environments that don't meet the prerequisites (like having TCP routers installed and enabled).

4. Do nothing about the syslog sink tests.  These tests will run like they do today and require uptimer to run on a system with a Go toolchain installed, but the pushability tests will be packaged in and can run without external dependencies.  This is a smaller change, but has the side effect of making the push code look different for the app pushability tests and the syslog sink tests, which isn't great.

Let me know if the team has further thoughts @davewalter and @Birdrock

**Comment by acosta11** [comment]
Hi @zmb3 ,

Thanks for the thorough update here. We think the relative stability of the rfc5424 package makes the new option 1. sound good to us.

@davewalter and @Birdrock feel free to chime in as well.

Thanks,
Andrew and @jamespollard8
