### ISSUE TITLE
Capture ctrl-c, finish current While

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/uptimer#5]
Hey All,

Great tool (used this outside of CI to do a bunch of performance runs). I had to ctrl-c out of a long running process (it was never going to finish). Would you all be open to having the uptimer capture ctrl-c and exit after a while has finished. Two ctrl-c's in a row would obviously forcefully exit.

**Comment by dsabeti** [comment]
Hey @zachgersh, this probably makes sense, but I need to suss out some details.

It sounds like you're suggesting that, when the user hits Ctrl-C, uptimer stops running the uptime measurements, but allows the `while` command to continue. Is that right? 

(An alternative approach would be for uptimer to pass through the signal to the `while` command to ask it to shutdown. Sounds dangerous of if the `while` command is a `bosh deploy`.)

Also, you can specify a list of commands for uptimer to use as the `while` command. If the user cancels with Ctrl-C, I _think_ we'd want uptimer to run all of the `while` commands, but another approach might be to let the current command finish, but not initiate the subsequent commands.

**Comment by zachgersh** [comment]
@dsabeti - I would like it to stop running the current `while` it is on and then exit printing out the uptime measurements up to that point.

**Comment by heyjcollins** [comment]
Hey @zachgersh - is this still a feature you're interested in? Still relevant?
If so, please comment and reopen.

Thank you,

Josh
