### ISSUE TITLE
New Feature: Measure uptime of the "Firehose"

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/uptimer#9]
As an operator I want to ensure the "FIrehose" is highly available during an executed upgrade path. 

__AC__
1.  Include a nozzle that expects a flow of logs/metrics
1. Nozzle will need to be scaled to >=2 instances for HA purposes

**Comment by dsabeti** [comment]
Hey @ahevenor. I think this could be a good point to start discussing what it would look like for individual release teams to contribute uptime tests that are specific to components in their system. You might imagine that each CF release team has additional notions of "uptime" that they'd like to validate beyond what uptimer currently tests.

I'd like to hear from some of the other release PMs about things they'd like to validate during a rolling deploy. My ideal (perhaps not quite possible) would be for teams to "plug in" their own tests into uptimer.

Maybe one question to start would be: do you expect each release team to run these tests? Just the loggregator team?

**Comment by ahevenor** [comment]
Ideally I see Loggregator running a pipeline that performs uptimer across major version upgrades across an n-2 window. We just recently stood up a pipeline to do that "cross talk" test we added to CATs. I can see us a running a variety of platform specific concerns + uptimer in that pipeline.

**Comment by heyjcollins** [comment]
Hey @ahevenor,

I'm doing some issue cleanup in uptimer and see the last comment here was over a year ago so I'm going to close.
If you'd like to re-up on it please feel free to reopen and we can continue.

We would be open to a PR, but we're not lending our focus to uptimer ATM.

Cheers,

Josh
